LivrETS/Models/Fair.cs
/*
LivrETS - Centralized system that manages selling of pre-owned ETS goods.
Copyright (C) 2016  TribuTerre

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/> 
 */
using LivrETS.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LivrETS.Models
{
    /// <summary>
    /// Represents a TribuTerre books fair organised at each start
    /// of a new semester at the ETS.
    /// </summary>
    public class Fair
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        [Required]
        public string Trimester { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<FairStep> FairSteps { get; set; }

        [Required]
        public double CommissionOnSale { get; set; }

        [NotMapped]
        public FairStep Phase {
            get
            {
                DateTime now = DateTime.Now;

                FairSteps.OrderBy(stp => stp.StartDateTime);
                foreach (FairStep step in FairSteps)
                {
                    if (DateTime.Compare(now, step.StartDateTime) == 0)
                    {
                        return step;
                    }
                }
                
                return null;
            }
        }

        [NotMapped]
        public string LivrETSID => $"{Trimester}{StartDate.Year}";

        public Fair()
        {
            Offers = new List<Offer>();
            Sales = new List<Sale>();
            FairSteps = new List<FairStep>();
        }

        /// <summary>
        /// Constructor with start and end dates of the fair.
        /// </summary>
        /// <param name="start">Start date of the fair</param>
        /// <param name="end">End date of the fair</param>
        public Fair(DateTime start, DateTime end)
            : this()
        {
            if (end <= start)
            {
                throw new ArgumentException("End must be greater than start");
            }

            StartDate = start;
            EndDate = end;
        }

        public static bool CheckStatusFair()
        {
            List<UserViewModel> listUsersParicipateFair = null;
            //Fair fair = null;
            var now = DateTime.Now;

            using (var db = new ApplicationDbContext())
            {
                try
                {
                    listUsersParicipateFair = db.Database.SqlQuery<UserViewModel>(
                            "SELECT u.Email, u.FirstName, u.LastName " +
                            "FROM AspNetUsers u " +
                            "INNER JOIN Offers o ON u.Id = o.ApplicationUser_Id " +
                            "INNER JOIN Fairs f ON f.Id = o.Fair_Id " +
                            "WHERE o.ManagedByFair = 1 " +
                            "AND GETDATE() BETWEEN f.StartDate AND f.EndDate ").ToList();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

                Fair fair = (
                            from fairdb in db.Fairs
                            join fs in db.FairSteps on fairdb.Id equals fs.FairID
                            where fairdb.StartDate <= now && now <= fairdb.EndDate
                            select fairdb
                        ).FirstOrDefault();

                if (fair == null || listUsersParicipateFair == null)
                    return false;

                DateTime fairRetrievalStartDate = DateTime.Now.AddDays(-10000);
                try
                {
                    fairRetrievalStartDate = fair.FairSteps.Where(step =>
                                            step.Phase == "R").FirstOrDefault().StartDateTime;
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                

                if (DateTime.Compare(now.Date, fairRetrievalStartDate.Date) == 0)
                    return NotificationManager.getInstance().sendNotification(
                        new Notification(NotificationOptions.STARTFAIRRETREIVAL, listUsersParicipateFair)
                    );
                else if (DateTime.Compare(now.Date, fairRetrievalStartDate.Date.AddDays(7)) == 0)
                    return NotificationManager.getInstance().sendNotification(
                        new Notification(NotificationOptions.LATEFORRETREIVALAFTERAWEEK, listUsersParicipateFair)
                    );

                return true;

            }
           
        }

        public string TrimesterToString()
        {

            switch(this.Trimester){
                case "H":
                    return "Hiver";
                case "A":
                    return "Automne";
                case "E":
                    return "Été";
                default:
                    return "Pas définie";
            }
        }
    }

}

LivrETS/ViewModels/FairViewModels.cs
/*
LivrETS - Centralized system that manages selling of pre-owned ETS goods.
Copyright (C) 2016  TribuTerre

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using LivrETS.Models;

namespace LivrETS.ViewModels
{
    public class FairViewModel
    {
        public float CurrentStep { get; set; }
        public float NumberOfPhases { get; set; }
        public ApplicationUser User { get; set; }
        public Fair Fair { get; set; }
        public ICollection<Offer> UserOffers { get; set; }
        public ICollection<Offer> FairOffers { get; set; }
        public string UserBarCode { get; set; }
    }

    public class SellViewModel
    {
        public Fair Fair { get; set; }
    }

    public class RetrieveViewModel
    {
        public Fair Fair { get; set; }
    }
}

LivrETS/Controllers/FairController.cs
/*
LivrETS - Centralized system that manages selling of pre-owned ETS goods.
Copyright (C) 2016  TribuTerre

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LivrETS.ViewModels;
using LivrETS.Repositories;
using LivrETS.Models;
using LivrETS.Service;
using System.Net;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Web.Script.Serialization;

namespace LivrETS.Controllers
{
    [Authorize(Roles = "Administrator,Clerk")]
    public class FairController : Controller
    {
        private const int NUMBER_OF_STEPS = 2;
        private const int MAX_NUMBER_OF_STICKERS_PER_SHEET = 14;
        private const string CURRENT_STEP = "CurrentPhase";
        private const string SELLER = "Seller";
        private const string SELLER_PICKED_ARTICLES = "SellerPickedArticles";
        private const string LAST_NUMBER_OF_STICKERS_LEFT_ON_SHEET = "LastNumberOfStickersLeftOnSheet";

        private LivrETSRepository _repository;
        public LivrETSRepository Repository
        {
            get
            {
                if (_repository == null)
                    _repository = new LivrETSRepository();

                return _repository;
            }
        }

        // GET: /Fair/Pick
        [HttpGet]
        public ActionResult Pick()
        {
            var model = new FairViewModel();
            var currentFair = Repository.GetCurrentFair();
            var currentStep = 0;

            model.Fair            = currentFair;
            model.CurrentStep     = currentStep;
            model.NumberOfPhases  = NUMBER_OF_STEPS;
            Session[CURRENT_STEP] = currentStep;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Pick(FairViewModel model)
        {
            if (Session[CURRENT_STEP] == null)
                return RedirectToAction(nameof(Pick));

            int currentStep = (int)Session[CURRENT_STEP];
            Fair currentFair = Repository.GetCurrentFair();

            model.Fair = currentFair;
            model.NumberOfPhases = NUMBER_OF_STEPS;

            if (string.IsNullOrEmpty(model.UserBarCode) && currentStep == 0)
            {
                ModelState.AddModelError(nameof(FairViewModel.UserBarCode), "Veuillez indiquez le code à barres du vendeur.");
            }

            if (ModelState.IsValid)
            {
                switch (currentStep)
                {
                    case 0:
                        ApplicationUser seller = Repository.GetUserBy(BarCode: model.UserBarCode.Trim().ToUpper());

                        if (seller == null) return RedirectToAction(nameof(Pick));

                        Session[CURRENT_STEP] = 1;
                        Session[SELLER]       = seller.Id;
                        model.CurrentStep     = 1;
                        model.User            = seller;
                        model.UserOffers      = seller.Offers;
                        model.FairOffers      = currentFair.Offers;
                        break;

                    case 1:
                        if (Session[SELLER] == null) return RedirectToAction(nameof(Pick));
                        ApplicationUser seller1 = Repository.GetUserBy(Id: Session[SELLER] as string);
                        Session[SELLER_PICKED_ARTICLES] = 
                            currentFair.Offers.Intersect(seller1.Offers)
                            .Where(offer => offer.Article.FairState == ArticleFairState.PICKED)
                            .ToList()
                            .ConvertAll(new Converter<Offer, string>(offer => offer.Id.ToString()));

                        Session[CURRENT_STEP] = 2;
                        model.CurrentStep     = 2;
                        model.User            = seller1;
                        break;

                    case 2:
                        return RedirectToAction(nameof(Pick));
                }
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Sell()
        {
            SellViewModel model = new SellViewModel()
            {
                Fair = Repository.GetCurrentFair()
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Retrieve()
        {
            var model = new RetrieveViewModel()
            {
                Fair = Repository.GetCurrentFair()
            };

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Program()
        {
            Fair curentFair = Repository.GetCurrentFair();
            Fair nextFair = Repository.GetNextFair();

            return View((curentFair != null) ? curentFair : nextFair);
             
        }

        #region Ajax

        [HttpPost]
        public ActionResult OffersNotSold(string UserBarCode)
        {
            var barCode = UserBarCode.ToUpper().Trim();
            var user = Repository.GetUserBy(BarCode: barCode);
            var currentFair = Repository.GetCurrentFair();

            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            var offersNotSold = currentFair.Offers
                //.Where(offer => !offer.Sold)
                .Intersect(user.Offers);
            
            return  Json(from offer in offersNotSold
                         select new
                         {
                             id = TRIBSTD01Helper.LivrETSIDOf(user: user, article: offer.Article, fair: currentFair),
                             title = offer.Article.Title,
                             userFullName = user.FullName,
                             price = offer.Price,
                             sold = offer.Sold
                         },
                            contentType: "application/json"
                    );
        }

        [HttpPost]
        public ActionResult RetrieveArticles(ICollection<string> ids)
        {
            foreach (var id in ids)
            {
                TRIBSTD01Helper helper;
                try
                {
                    helper = new TRIBSTD01Helper(id.ToUpper().Trim());
                }
                catch (RegexNoMatchException ex)
                {
                    Console.WriteLine(ex.Message);
                    continue;
                }

                var offer = helper.GetOffer();
                Repository.AttachToContext(offer);
                offer.Article.MarkAsRetrieved();
                Repository.Update();

                //send notification mail
                /*NotificationManager.getInstance().sendNotification(
                    new Notification(NotificationOptions.ARTICLERETREIVEDCONFIRMATION,
                                Repository.GetOfferByUser(offer))
                    );*/
            }

            return Json(new { }, contentType: "application/json");
        }

        public ActionResult ConcludeSell(ICollection<string> ids)
        {
            bool noMatchExists = false;
            var fair = Repository.GetCurrentFair();
            var seller = Repository.GetUserBy(Id: User.Identity.GetUserId());
            var sale = new Sale()
            {
                Date = DateTime.Now,
            };

            var helpers = ids.ToList().ConvertAll(new Converter<string, TRIBSTD01Helper>(id =>
            {
                TRIBSTD01Helper helper = null;
                try
                {
                    helper = new TRIBSTD01Helper(id);
                }
                catch (RegexNoMatchException ex)
                {
                    noMatchExists = true;
                    Console.WriteLine(ex.Message);
                    return null;
                }

                return helper;
            }));

            if (noMatchExists)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            foreach (var helper in helpers)
            {
                var offer = helper.GetOffer();
                Repository.AttachToContext(offer);
                offer.Article.MarkAsSold();
                offer.MarkedSoldOn = DateTime.Now;
                sale.SaleItems.Add(new SaleItem()
                {
                    Offer = offer
                });
            }

            seller.Sales.Add(sale);
            fair.Sales.Add(sale);
            Repository.Update();
            return Json(new { }, contentType: "application/json");
        }

        [HttpPost]
        public ActionResult ConcludeSellTest(ICollection<string> offerIds, string fairId = null)
        {
            bool noMatchExists = false, status=false;

            Fair fair = (fairId != null)?Repository.GetFairById(fairId):
                Repository.GetCurrentFair();

            if(fair == null)
                return Json(new {
                    status = status,
                    message = "La foire concernée n'a pas été retrouvé"
                }, contentType: "application/json");


LivrETS/Views/Fair/Pick.cshtml
@*
    LivrETS - Centralized system that manages selling of pre-owned ETS goods.
    Copyright (C) 2016  TribuTerre

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>
*@
@using LivrETS.ViewModels
@using LivrETS.Models
@model FairViewModel
@{
    ViewBag.Title = "Cueillette";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var progress = Model.CurrentStep / Model.NumberOfPhases * 100f;
    string inputValue = Model.CurrentStep == 2 ? "Terminer" : "Suivant >";
}
@section Styles {
    <style>
        div.group-error {
            margin: 10% 0;
            min-height: 200px;
        }

        div.group-error h1 {
            font-size: 70px;
        }
    </style>
}
<div class="content">
    <div class="container">
        @if (Model.Fair == null /*|| Model.Fair.Phase != FairPhase.PICKING*/)
        {
            <div class="row">
                <div class="group-error text-center">
                    <div class="col-md-12">
                        <h1 class="primary-color">Désolé!</h1>
                    </div>
                    <div class="col-md-12">
                        <h2>
                            Vous n'&ecirc;tes pas pr&eacute;sentement en
                            p&eacute;riode de <span class="primary-color">cueillette</span>  =(
                        </h2>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="page-header">
                <h1>Cueillir des articles <small>Pour la Foire @Model.Fair.LivrETSID</small></h1>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="@progress" aria-valuemin="0" 
                             aria-valuemax="100" style="width: @progress%; min-width: 2em;">
                            @progress%
                        </div>
                    </div>
                </div>
            </div>

            using (Html.BeginForm("Pick", "Fair", FormMethod.Post, new { @class = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @switch ((int)(Model.CurrentStep))
                    {
                        case 0:
                            <h3>Num&eacute;risez ou entrez manuellement<br />le code &agrave; barres de la<br />
                                carte &eacute;tudiante du vendeur.
                            </h3>
                            <div class="row">
                                <div class="col-md-4">
                                    @Html.TextBoxFor(model => model.UserBarCode,
                                        new { @class = "form-control", placeholder = "Ex: FF000000",
                                            autofocus = "autofocus" })
                                </div>
                                <div class="col-md-12">
                                    @Html.ValidationMessageFor(model => model.UserBarCode, "", 
                                        new { @class = "text-danger" })
                                </div>
                            </div>
                            break;

                        case 1:
                            <div class="row">
                                <div class="col-md-4">
                                    <input type="text" class="form-control" id="article-code-input" 
                                           placeholder="Code à barres ou ISBN de l'article" autofocus />
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Articles par le vendeur</h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="table-responsive">
                                        <table id="notpicked-table" class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Type</th>
                                                    <th>Titre</th>
                                                    <th>ISBN ou Code ou Mod&egrave;le</th>
                                                    <th>Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var offer in Model.FairOffers.Intersect(Model.UserOffers))
                                                {
                                                    <tr>
                                                        <td>@offer.Article.LivrETSID</td>
                                                        <td>@offer.Article.TypeName</td>
                                                        <td>@offer.Article.Title</td>
                                                        <td>
                                                            @switch (offer.Article.ArticleCode)
                                                            {
                                                                case Article.BOOK_CODE:
                                                                    @((offer.Article as Book).ISBN)
                                                                    break;
                                                                case Article.CALCULATOR_CODE:
                                                                    @((offer.Article as Calculator).Model.ToString())
                                                                    break;
                                                                case Article.COURSE_NOTES_CODE:
                                                                    @((offer.Article as CourseNotes).BarCode)
                                                                    break;
                                                            }
                                                        </td>
                                                        <td>
                                                            <button class="btn btn-sm btn-success pick-article-btn" 
                                                                    data-article-id="@offer.Article.Id" type="button">
                                                                        Cueillir
                                                            </button>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <br />

                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Articles re&ccedil;us pour la Foire</h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="table-responsive">
                                        <table id="picked-articles-table" class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Type</th>
                                                    <th>Titre</th>
                                                    <th>ISBN ou Code ou Mod&egrave;le</th>
                                                    <th>Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            break;

                        case 2:
                            <div class="row">
                                <div class="col-md-6">
                                    <span>Nombre d'&eacute;tiquettes restantes sur la feuille</span>
                                    <input type="number" class="form-control" style="width: 70px; display: inline;" />
                                    <button id="btn-preview" type="button" class="btn btn-default">Pr&eacute;visualiser</button>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                                <div class="col-md-6" style="min-height: 500px; border: 1px black solid; border-radius: 2px;">
                                    <iframe id="embed-preview" src="" style="width: 100%; height: 500px;" ></iframe>
                                </div>
                            </div>
                            break;
                    }
                </div>

                <div class="row">
                    <div class="@(Model.CurrentStep == 1 ? "col-md-8" : "col-md-6")">
                        <input type="submit" class="btn btn-primary pull-right" value="@inputValue" />
                        @if (Model.CurrentStep == 2)
                        {
                            <button type="button" id="btn-print" class="btn btn-default pull-right" 
                                    style="margin-right: 5px;" disabled>Imprimer</button>
                        }
                    </div>
                </div>

        <!-- MODALS -->
                <div id="pick-confirm-dialog" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class="modal-body">
                                <p>
                                    V&eacute;rifiez que vous avez bien pris physiquement l'article avant de
                                    le marquer comme cueillis.
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                                <button id="btn-confirm-pick" type="button" class="btn btn-primary">
                                    <i class="fa fa-spinner fa-pulse fa-fw hide"></i>
                                    <span class="sr-only">Loading...</span>
                                    Cueillir
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
        <!-- END MODALS -->
            }

            @section Scripts {
                <script src="~/Scripts/fair/pick.js"></script>
            }
        }
    </div>
</div>